/-
Copyright (c) 2026 Asher Yan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asher Yan with Codex
-/
module

public import CryptBoolean.Carlet.Chapter02.Affine
public import Mathlib.RingTheory.Ideal.Basic

/-!
# Carlet Chapter 4 algebraic immunity

Boolean-function annihilators, their principal ideal, algebraic immunity, affine invariance, and
the low-degree relation equivalence from Carlet Section 4.1.6.
-/

open scoped BooleanCube

@[expose] public section

namespace CryptBoolean

variable {n : ℕ}

/-- The support of a pointwise product is the intersection of the two supports. -/
theorem support_mul (f g : BooleanFunction n) :
    support (f * g) = support f ∩ support g := by
  ext x
  simp only [mem_support, Finset.mem_inter, Pi.mul_apply]
  constructor
  · intro h
    have hne : f x * g x ≠ 0 := by rw [h]; exact one_ne_zero
    exact ⟨Fin.eq_one_of_ne_zero _ (mul_ne_zero_iff.mp hne).1,
      Fin.eq_one_of_ne_zero _ (mul_ne_zero_iff.mp hne).2⟩
  · rintro ⟨hf, hg⟩
    simp [hf, hg]

/-- Every binary-valued function is idempotent under pointwise multiplication. -/
theorem booleanFunction_mul_self (f : BooleanFunction n) :
    f * f = f := by
  funext x
  change f x * f x = f x
  by_cases hx : f x = 0
  · simp [hx]
  · have hx1 : f x = (1 : FABL.𝔽₂) := Fin.eq_one_of_ne_zero _ hx
    rw [hx1]
    exact one_mul 1

/-- A Boolean function and its complement have disjoint pointwise product. -/
theorem booleanFunction_mul_complement (f : BooleanFunction n) :
    f * (f + 1) = 0 := by
  rw [mul_add, mul_one, booleanFunction_mul_self, ZModModule.add_self]

/-- A nonzero Boolean function whose pointwise product with `f` vanishes. -/
def IsAnnihilator (f g : BooleanFunction n) : Prop :=
  g ≠ 0 ∧ f * g = 0

/-- The ideal of all (possibly zero) annihilators of `f`, generated by its complement. -/
noncomputable def annihilatorIdeal (f : BooleanFunction n) :
    Ideal (BooleanFunction n) :=
  Ideal.span {f + 1}

/-- Membership in the annihilator ideal is exactly vanishing of the pointwise product with `f`. -/
theorem mem_annihilatorIdeal_iff (f g : BooleanFunction n) :
    g ∈ annihilatorIdeal f ↔ f * g = 0 := by
  constructor
  · intro hg
    obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp hg
    rw [← ha]
    calc
      f * (a * (f + 1)) = a * (f * (f + 1)) := by ac_rfl
      _ = 0 := by rw [booleanFunction_mul_complement, mul_zero]
  · intro hg
    apply Ideal.mem_span_singleton'.mpr
    refine ⟨g, ?_⟩
    calc
      g * (f + 1) = g * f + g := by rw [mul_add, mul_one]
      _ = f * g + g := by rw [mul_comm g f]
      _ = 0 + g := by rw [hg]
      _ = g := zero_add g

/-- Nonzero elements of the annihilator ideal are precisely Carlet annihilators. -/
theorem isAnnihilator_iff_mem_annihilatorIdeal (f g : BooleanFunction n) :
    IsAnnihilator f g ↔ g ≠ 0 ∧ g ∈ annihilatorIdeal f := by
  rw [IsAnnihilator, mem_annihilatorIdeal_iff]

/-- A witness for algebraic immunity annihilates either `f` or its complement. -/
def IsAlgebraicImmunityWitness (f g : BooleanFunction n) : Prop :=
  IsAnnihilator f g ∨ IsAnnihilator (f + 1) g

/-- The finite family over which algebraic immunity takes its minimum. -/
noncomputable def algebraicImmunityCandidates
    (f : BooleanFunction n) : Finset (BooleanFunction n) :=
  by
    classical
    exact Finset.univ.filter (IsAlgebraicImmunityWitness f)

/-- Membership in the candidate family is the defining annihilator disjunction. -/
theorem mem_algebraicImmunityCandidates (f g : BooleanFunction n) :
    g ∈ algebraicImmunityCandidates f ↔ IsAlgebraicImmunityWitness f g := by
  classical
  simp [algebraicImmunityCandidates]

/-- Every Boolean function has a nonzero annihilator on one side of the complement pair. -/
theorem algebraicImmunityCandidates_nonempty (f : BooleanFunction n) :
    (algebraicImmunityCandidates f).Nonempty := by
  classical
  by_cases hf : f = 0
  · refine ⟨1, (mem_algebraicImmunityCandidates f 1).2 ?_⟩
    left
    subst f
    exact ⟨one_ne_zero, zero_mul 1⟩
  · refine ⟨f, (mem_algebraicImmunityCandidates f f).2 ?_⟩
    right
    refine ⟨hf, ?_⟩
    rw [mul_comm]
    exact booleanFunction_mul_complement f

/-- Algebraic immunity is the least algebraic degree of a nonzero annihilator of `f` or `f+1`. -/
noncomputable def algebraicImmunity (f : BooleanFunction n) : ℕ :=
  (algebraicImmunityCandidates f).inf'
    (algebraicImmunityCandidates_nonempty f)
    FABL.functionAlgebraicDegree

/-- Algebraic immunity is bounded by the degree of every annihilator witness. -/
theorem algebraicImmunity_le_functionAlgebraicDegree
    (f g : BooleanFunction n) (hg : IsAlgebraicImmunityWitness f g) :
    algebraicImmunity f ≤ FABL.functionAlgebraicDegree g := by
  classical
  exact Finset.inf'_le _ ((mem_algebraicImmunityCandidates f g).2 hg)

/-- The finite witness family contains an annihilator attaining algebraic immunity. -/
theorem exists_witness_functionAlgebraicDegree_eq_algebraicImmunity
    (f : BooleanFunction n) :
    ∃ g : BooleanFunction n, IsAlgebraicImmunityWitness f g ∧
      FABL.functionAlgebraicDegree g = algebraicImmunity f := by
  classical
  obtain ⟨g, hg, hdegree⟩ := Finset.exists_mem_eq_inf'
    (s := algebraicImmunityCandidates f)
    (algebraicImmunityCandidates_nonempty f)
    FABL.functionAlgebraicDegree
  exact ⟨g, (mem_algebraicImmunityCandidates f g).1 hg, hdegree.symm⟩

/-- Affine input reindexing preserves the annihilator relation. -/
theorem IsAnnihilator.comp_affineEquiv
    {f g : BooleanFunction n} (h : IsAnnihilator f g)
    (L : FABL.F₂Cube n ≃ᵃ[FABL.𝔽₂] FABL.F₂Cube n) :
    IsAnnihilator (f ∘ L) (g ∘ L) := by
  constructor
  · intro hzero
    apply h.1
    funext x
    have hx := congrFun hzero (L.symm x)
    simpa using hx
  · funext x
    simpa [Function.comp_apply] using congrFun h.2 (L x)

/-- Affine input reindexing transports algebraic-immunity witnesses. -/
theorem IsAlgebraicImmunityWitness.comp_affineEquiv
    {f g : BooleanFunction n} (h : IsAlgebraicImmunityWitness f g)
    (L : FABL.F₂Cube n ≃ᵃ[FABL.𝔽₂] FABL.F₂Cube n) :
    IsAlgebraicImmunityWitness (f ∘ L) (g ∘ L) := by
  rcases h with h | h
  · exact Or.inl (h.comp_affineEquiv L)
  · right
    have hcomp := h.comp_affineEquiv L
    refine ⟨hcomp.1, ?_⟩
    funext x
    simpa [Function.comp_apply] using congrFun hcomp.2 x

/-- One half of affine invariance of algebraic immunity. -/
theorem algebraicImmunity_comp_affineEquiv_le
    (f : BooleanFunction n)
    (L : FABL.F₂Cube n ≃ᵃ[FABL.𝔽₂] FABL.F₂Cube n) :
    algebraicImmunity (f ∘ L) ≤ algebraicImmunity f := by
  obtain ⟨g, hg, hdegree⟩ :=
    exists_witness_functionAlgebraicDegree_eq_algebraicImmunity f
  calc
    algebraicImmunity (f ∘ L) ≤
        FABL.functionAlgebraicDegree (g ∘ L) :=
      algebraicImmunity_le_functionAlgebraicDegree
        (f ∘ L) (g ∘ L) (hg.comp_affineEquiv L)
    _ = FABL.functionAlgebraicDegree g :=
      FABL.functionAlgebraicDegree_comp_affineEquiv g L
    _ = algebraicImmunity f := hdegree

/-- Algebraic immunity is invariant under affine equivalence. -/
theorem algebraicImmunity_comp_affineEquiv
    (f : BooleanFunction n)
    (L : FABL.F₂Cube n ≃ᵃ[FABL.𝔽₂] FABL.F₂Cube n) :
    algebraicImmunity (f ∘ L) = algebraicImmunity f := by
  apply Nat.le_antisymm
    (algebraicImmunity_comp_affineEquiv_le f L)
  have h := algebraicImmunity_comp_affineEquiv_le (f ∘ L) L.symm
  have hcomp : (f ∘ L) ∘ L.symm = f := by
    funext x
    simp
  rw [hcomp] at h
  exact h

/-- A nonzero low-degree relation `f*g=h` exists exactly when `f` or `f+1` has a nonzero
annihilator of the same degree bound. -/
theorem exists_lowDegreeRelation_iff_exists_algebraicImmunityWitness
    (f : BooleanFunction n) (d : ℕ) :
    (∃ g h : BooleanFunction n,
      g ≠ 0 ∧
      FABL.functionAlgebraicDegree g ≤ d ∧
      FABL.functionAlgebraicDegree h ≤ d ∧
      f * g = h) ↔
    (∃ q : BooleanFunction n,
      q ≠ 0 ∧
      FABL.functionAlgebraicDegree q ≤ d ∧
      (f * q = 0 ∨ (f + 1) * q = 0)) := by
  constructor
  · rintro ⟨g, h, hg, hgdegree, hhdegree, hrelation⟩
    by_cases hgh : g = h
    · refine ⟨g, hg, hgdegree, Or.inr ?_⟩
      rw [add_mul, one_mul, hrelation, ← hgh, ZModModule.add_self]
    · refine ⟨g + h, ?_, ?_, Or.inl ?_⟩
      · intro hzero
        apply hgh
        exact (eq_neg_of_add_eq_zero_left hzero).trans (ZModModule.neg_eq_self h)
      · exact (FABL.functionAlgebraicDegree_add_le_max g h).trans
          (max_le hgdegree hhdegree)
      · have hfh : f * h = h := by
          calc
            f * h = f * (f * g) := by rw [hrelation]
            _ = (f * f) * g := by rw [mul_assoc]
            _ = f * g := by rw [booleanFunction_mul_self]
            _ = h := hrelation
        rw [mul_add, hrelation, hfh, ZModModule.add_self]
  · rintro ⟨q, hq, hqdegree, hzero | hzero⟩
    · exact ⟨q, 0, hq, hqdegree, by simp, hzero⟩
    · refine ⟨q, q, hq, hqdegree, hqdegree, ?_⟩
      have hsum : f * q + q = 0 := by
        simpa only [add_mul, one_mul] using hzero
      calc
        f * q = f * q + 0 := (add_zero _).symm
        _ = f * q + (q + q) := by rw [ZModModule.add_self]
        _ = (f * q + q) + q := by rw [add_assoc]
        _ = 0 + q := by rw [hsum]
        _ = q := zero_add q

end CryptBoolean
