/-
Copyright (c) 2026 Asher Yan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asher Yan with Codex
-/
module

public import CryptBoolean.Carlet.Chapter06.HadamardDifferenceSet
public import Mathlib.Combinatorics.SimpleGraph.Cayley
public import Mathlib.Combinatorics.SimpleGraph.StronglyRegular

/-!
# Boolean Cayley graphs of bent functions

The support difference-set parameters give the exact strongly regular graph
parameters for a bent function normalized by `f 0 = 0`.
-/

open scoped BooleanCube

@[expose] public section

namespace CryptBoolean

variable {n : ℕ}

/-- The additive Cayley graph generated by the support of a Boolean function. -/
def booleanCayleyGraph (f : BooleanFunction n) :
    SimpleGraph (FABL.F₂Cube n) :=
  SimpleGraph.addCayley (↑(support f) : Set (FABL.F₂Cube n))

noncomputable local instance booleanCayleyGraphDecidableRel
    (f : BooleanFunction n) : DecidableRel (booleanCayleyGraph f).Adj :=
  Classical.decRel _

/-- Two distinct vertices are adjacent exactly when their sum lies in the
Boolean support. -/
theorem booleanCayleyGraph_adj
    (f : BooleanFunction n) (x y : FABL.F₂Cube n) :
    (booleanCayleyGraph f).Adj x y ↔ x ≠ y ∧ f (x + y) = 1 := by
  simp [booleanCayleyGraph, SimpleGraph.addCayley_adj, mem_support,
    ZModModule.neg_eq_self, add_comm]

private theorem ne_of_boolean_sum_eq_one
    (f : BooleanFunction n) (hfZero : f 0 = 0)
    {x y : FABL.F₂Cube n} (hxy : f (x + y) = 1) :
    x ≠ y := by
  intro h
  subst y
  rw [ZModModule.add_self, hfZero] at hxy
  exact zero_ne_one hxy

private noncomputable def differenceCommonNeighborEquiv
    (f : BooleanFunction n) (hfZero : f 0 = 0)
    (v w : FABL.F₂Cube n) :
    {x : FABL.F₂Cube n //
        x ∈ (support f).filter fun x ↦ x + (v + w) ∈ support f} ≃
      (booleanCayleyGraph f).commonNeighbors v w where
  toFun x := by
    refine ⟨v + x.1, ?_⟩
    have hx := Finset.mem_filter.mp x.2
    have hxOne : f x.1 = 1 := (mem_support f x.1).1 hx.1
    have hshiftOne : f (x.1 + (v + w)) = 1 :=
      (mem_support f (x.1 + (v + w))).1 hx.2
    change (booleanCayleyGraph f).Adj v (v + x.1) ∧
      (booleanCayleyGraph f).Adj w (v + x.1)
    constructor
    · apply (booleanCayleyGraph_adj f v (v + x.1)).2
      have hsum : v + (v + x.1) = x.1 := by
        rw [← add_assoc, ZModModule.add_self, zero_add]
      exact ⟨ne_of_boolean_sum_eq_one f hfZero (by simpa [hsum] using hxOne),
        by simpa [hsum] using hxOne⟩
    · apply (booleanCayleyGraph_adj f w (v + x.1)).2
      have hsum : w + (v + x.1) = x.1 + (v + w) := by ac_rfl
      exact ⟨ne_of_boolean_sum_eq_one f hfZero
          (by simpa [hsum] using hshiftOne),
        by simpa [hsum] using hshiftOne⟩
  invFun z := by
    refine ⟨v + z.1, ?_⟩
    have hz := z.2
    change (booleanCayleyGraph f).Adj v z.1 ∧
      (booleanCayleyGraph f).Adj w z.1 at hz
    have hv := (booleanCayleyGraph_adj f v z.1).1 hz.1
    have hw := (booleanCayleyGraph_adj f w z.1).1 hz.2
    rw [Finset.mem_filter]
    refine ⟨(mem_support f (v + z.1)).2 hv.2, ?_⟩
    apply (mem_support f ((v + z.1) + (v + w))).2
    have hsum : (v + z.1) + (v + w) = w + z.1 := by
      rw [show (v + z.1) + (v + w) = (v + v) + (z.1 + w) by ac_rfl,
        ZModModule.add_self, zero_add, add_comm]
    simpa [hsum] using hw.2
  left_inv x := by
    apply Subtype.ext
    change v + (v + x.1) = x.1
    rw [← add_assoc, ZModModule.add_self, zero_add]
  right_inv z := by
    apply Subtype.ext
    change v + (v + z.1) = z.1
    rw [← add_assoc, ZModModule.add_self, zero_add]

/-- Common neighbors in the Boolean Cayley graph are counted by the
corresponding support difference multiplicity. -/
theorem card_commonNeighbors_booleanCayleyGraph
    (f : BooleanFunction n) (hfZero : f 0 = 0)
    (v w : FABL.F₂Cube n) :
    Nat.card ((booleanCayleyGraph f).commonNeighbors v w) =
      differenceMultiplicity (support f) (v + w) := by
  classical
  rw [differenceMultiplicity]
  calc
    Nat.card ((booleanCayleyGraph f).commonNeighbors v w) =
        Nat.card
          {x : FABL.F₂Cube n //
            x ∈ (support f).filter fun x ↦ x + (v + w) ∈ support f} :=
      Nat.card_congr
        (differenceCommonNeighborEquiv f hfZero v w).symm
    _ = ((support f).filter fun x ↦
        x + (v + w) ∈ support f).card :=
      Nat.subtype_card _ (fun _ ↦ Iff.rfl)

/-- The Boolean Cayley graph has degree equal to the support size when the
origin is outside the support. -/
theorem degree_booleanCayleyGraph
    (f : BooleanFunction n) (hfZero : f 0 = 0)
    (v : FABL.F₂Cube n) :
    (booleanCayleyGraph f).degree v = (support f).card := by
  have hcommon := card_commonNeighbors_booleanCayleyGraph f hfZero v v
  have hfilter :
      (support f).filter (fun x ↦ f x = 1) = support f := by
    ext x
    simp [mem_support]
  rw [← SimpleGraph.card_neighborSet_eq_degree]
  rw [← Nat.card_eq_fintype_card]
  simpa [SimpleGraph.commonNeighbors, differenceMultiplicity,
    ZModModule.add_self, hfilter] using hcommon

/-- A bent function normalized by `f(0)=0` has a strongly regular Boolean
Cayley graph with its exact Hadamard difference-set parameters. -/
theorem isSRGWith_booleanCayleyGraph_of_isBent
    (f : BooleanFunction n) (hnEven : Even n) (hn : 2 ≤ n)
    (hfZero : f 0 = 0) (hf : IsBent f) :
    (booleanCayleyGraph f).IsSRGWith
      (2 ^ n) (support f).card
      ((support f).card - 2 ^ (n - 2))
      ((support f).card - 2 ^ (n - 2)) := by
  classical
  let G := booleanCayleyGraph f
  have hDifferenceSet :=
    (isBent_iff_support_isHadamardDifferenceSet f hnEven hn).1 hf
  refine
    { card := card_f₂Cube n
      regular := ?_
      of_adj := ?_
      of_not_adj := ?_ }
  · intro v
    exact degree_booleanCayleyGraph f hfZero v
  · intro v w hvw
    have hvwNe : v ≠ w := hvw.ne
    have hdirection : v + w ≠ 0 := by
      intro hzero
      apply hvwNe
      exact (add_eq_zero_iff_eq_neg.mp hzero).trans
        (ZModModule.neg_eq_self w)
    rw [← Nat.card_eq_fintype_card,
      card_commonNeighbors_booleanCayleyGraph f hfZero]
    exact hDifferenceSet.2 (v + w) hdirection
  · intro v w hvw _hnotAdjacent
    have hdirection : v + w ≠ 0 := by
      intro hzero
      apply hvw
      exact (add_eq_zero_iff_eq_neg.mp hzero).trans
        (ZModModule.neg_eq_self w)
    rw [← Nat.card_eq_fintype_card,
      card_commonNeighbors_booleanCayleyGraph f hfZero]
    exact hDifferenceSet.2 (v + w) hdirection

end CryptBoolean
