/-
Copyright (c) 2026 Asher Yan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asher Yan with Codex
-/
module

public import CryptBoolean.Carlet.Chapter04.SupportDualDistance
public import CryptBoolean.Carlet.Chapter06.Dual

/-!
# The linear code carried by the support of a Boolean function

Carlet Proposition 16: the support-column code characterizes bent functions.
-/

open scoped BigOperators BooleanCube

@[expose] public section

namespace CryptBoolean

variable {n : ℕ}

/-- The codeword obtained by evaluating the linear form `x ↦ v · x` on the
support of `f`. -/
def supportCodeMap (f : BooleanFunction n) :
    FABL.F₂Cube n →ₗ[FABL.𝔽₂] (↥(support f) → FABL.𝔽₂) where
  toFun v x := FABL.f₂DotProduct v x.1
  map_add' v w := by
    funext x
    exact add_dotProduct v w x.1
  map_smul' c v := by
    funext x
    exact smul_dotProduct c v x.1

/-- The support-column linear code generated by the coordinate rows of the
support matrix. -/
def supportCode (f : BooleanFunction n) :
    Submodule FABL.𝔽₂ (↥(support f) → FABL.𝔽₂) :=
  LinearMap.range (supportCodeMap f)

/-- The Hamming weight of the support-code word indexed by `v`. -/
def supportCodewordWeight (f : BooleanFunction n) (v : FABL.F₂Cube n) : ℕ :=
  hammingNorm (supportCodeMap f v)

/-- The support-code word indexed by zero has weight zero. -/
@[simp] theorem supportCodewordWeight_zero (f : BooleanFunction n) :
    supportCodewordWeight f 0 = 0 := by
  simp [supportCodewordWeight]

/-- A support-code word counts support points on which its defining linear
form is one. -/
theorem supportCodewordWeight_eq_card_filter
    (f : BooleanFunction n) (v : FABL.F₂Cube n) :
    supportCodewordWeight f v =
      ((support f).filter fun x ↦ FABL.f₂DotProduct v x = 1).card := by
  classical
  rw [supportCodewordWeight, hammingNorm, Finset.univ_eq_attach]
  apply Finset.card_bij (fun x _hx ↦ x.1)
  · intro x hx
    rw [Finset.mem_filter] at hx ⊢
    exact ⟨x.2, Fin.eq_one_of_ne_zero _ hx.2⟩
  · intro x _hx y _hy hxy
    exact Subtype.ext hxy
  · intro x hx
    refine ⟨⟨x, (Finset.mem_filter.mp hx).1⟩, ?_, rfl⟩
    rw [Finset.mem_filter]
    refine ⟨Finset.mem_attach _ _, ?_⟩
    change FABL.f₂DotProduct v x ≠ 0
    rw [(Finset.mem_filter.mp hx).2]
    exact one_ne_zero

/-- The character sum over the support is its cardinality minus twice the
support-code word weight. -/
theorem codeCharacterSum_support_eq_card_sub_two_weight
    (f : BooleanFunction n) (v : FABL.F₂Cube n) :
    codeCharacterSum (support f) v =
      ((support f).card : ℝ) - 2 * supportCodewordWeight f v := by
  classical
  rw [codeCharacterSum, supportCodewordWeight_eq_card_filter]
  calc
    ∑ x ∈ support f, FABL.vectorWalshCharacter v x =
        ∑ x ∈ support f,
          (1 - 2 * (if FABL.f₂DotProduct v x = 1 then (1 : ℝ) else 0)) := by
      apply Finset.sum_congr rfl
      intro x _hx
      by_cases hdot : FABL.f₂DotProduct v x = 1
      · simp [FABL.vectorWalshCharacter_apply, hdot]
        norm_num
      · have hzero : FABL.f₂DotProduct v x = 0 := by
          by_contra hne
          exact hdot (Fin.eq_one_of_ne_zero _ hne)
        simp [FABL.vectorWalshCharacter_apply, hzero]
    _ = (support f).card -
        2 * (((support f).filter fun x ↦
          FABL.f₂DotProduct v x = 1).card : ℝ) := by
      rw [Finset.sum_sub_distrib]
      simp only [Finset.sum_const, nsmul_eq_mul]
      rw [← Finset.mul_sum]
      simp

/-- For a nonzero frequency, four times the support-code word weight is the
difference between the corresponding and zero-frequency Walsh coefficients,
shifted by the cube cardinality. -/
theorem four_mul_supportCodewordWeight_eq
    (f : BooleanFunction n) (v : FABL.F₂Cube n) (hv : v ≠ 0) :
    (4 : ℤ) * supportCodewordWeight f v =
      2 ^ n + walshTransform f v - walshTransform f 0 := by
  have hsupport := codeCharacterSum_support_eq_card_sub_two_weight f v
  have hwalsh :=
    walshTransform_cast_eq_neg_two_mul_codeCharacterSum_support f v hv
  have hzero := walshTransform_zero_eq_two_pow_sub_two_weight f
  rw [hsupport] at hwalsh
  rw [hammingWeight_eq_card_support] at hzero
  have hzeroReal := congrArg (fun z : ℤ ↦ (z : ℝ)) hzero
  norm_num only [Int.cast_sub, Int.cast_pow, Int.cast_ofNat, Int.cast_mul,
    Int.cast_natCast] at hzeroReal
  have hreal :
    (4 : ℝ) * supportCodewordWeight f v =
      (2 : ℝ) ^ n + walshTransform f v - walshTransform f 0 := by
    linarith
  exact_mod_cast hreal

/-- The exact two-nonzero-weight condition for the support-column code. -/
def SupportCodeHasExactlyTwoNonzeroWeights (f : BooleanFunction n) : Prop :=
  let first := 2 ^ (n - 2)
  let second := hammingWeight f - first
  (∀ c : supportCode f, c ≠ 0 →
      hammingNorm c.1 = first ∨ hammingNorm c.1 = second) ∧
    (∃ c : supportCode f, c ≠ 0 ∧ hammingNorm c.1 = first) ∧
    (∃ c : supportCode f, c ≠ 0 ∧ hammingNorm c.1 = second)

/-- The support code has full ambient dimension exactly when its defining
linear map is injective. -/
theorem finrank_supportCode_eq_n_iff_injective
    (f : BooleanFunction n) :
    Module.finrank FABL.𝔽₂ (supportCode f) = n ↔
      Function.Injective (supportCodeMap f) := by
  constructor
  · intro hrank
    rw [← LinearMap.ker_eq_bot]
    apply Submodule.finrank_eq_zero.mp
    have hrankNull := LinearMap.finrank_range_add_finrank_ker (supportCodeMap f)
    change Module.finrank FABL.𝔽₂ (supportCode f) +
      Module.finrank FABL.𝔽₂ (LinearMap.ker (supportCodeMap f)) = _ at hrankNull
    rw [hrank] at hrankNull
    simpa using hrankNull
  · intro hinjective
    change Module.finrank FABL.𝔽₂ (LinearMap.range (supportCodeMap f)) = n
    rw [LinearMap.finrank_range_of_inj hinjective]
    simp

private theorem nonlinearity_le_hammingWeight (f : BooleanFunction n) :
    nonlinearity f ≤ hammingWeight f := by
  unfold nonlinearity
  have hle := Finset.inf'_le
    (fun p : FABL.𝔽₂ × FABL.F₂Cube n ↦
      hammingDistance f (FABL.affineFunction p.1 p.2))
    (Finset.mem_univ (0, 0))
  have hzero :
      FABL.affineFunction (0 : FABL.𝔽₂) (0 : FABL.F₂Cube n) = 0 := by
    funext x
    simp [FABL.affineFunction, FABL.f₂DotProduct]
  rw [hzero] at hle
  simpa [hammingDistance_eq_hammingWeight_add] using hle

private theorem two_pow_sub_two_lt_hammingWeight_of_isBent
    (f : BooleanFunction n) (hf : IsBent f) (hnEven : Even n) (hn : 4 ≤ n) :
    2 ^ (n - 2) < hammingWeight f := by
  have hnonlinearity :=
    nonlinearity_eq_two_pow_sub_two_pow_half_of_isBent f hf (by omega)
  have hle := nonlinearity_le_hammingWeight f
  have hexponents : n / 2 - 1 < n - 2 := by
    rcases hnEven with ⟨k, rfl⟩
    omega
  have hpowers : 2 ^ (n / 2 - 1) < 2 ^ (n - 2) :=
    Nat.pow_lt_pow_right (by omega) hexponents
  have hsplit : 2 ^ (n - 1) = 2 * 2 ^ (n - 2) := by
    rw [show n - 1 = (n - 2) + 1 by omega, pow_succ]
    exact Nat.mul_comm _ _
  have hfirst : 2 ≤ 2 ^ (n - 2) := by
    have hexponent : 1 ≤ n - 2 := by omega
    simpa using
      (Nat.pow_le_pow_right (n := 2) (by omega : 0 < 2) hexponent)
  omega

private theorem exists_nonzero_eq_one_of_isBent
    (f : BooleanFunction n) (hf : IsBent f) (hnEven : Even n) (hn : 4 ≤ n) :
    ∃ v : FABL.F₂Cube n, v ≠ 0 ∧ f v = 1 := by
  have hcard : 1 < (support f).card := by
    rw [← hammingWeight_eq_card_support]
    have hfirst :=
      two_pow_sub_two_lt_hammingWeight_of_isBent f hf hnEven hn
    have hfirstTwo : 2 ≤ 2 ^ (n - 2) := by
      have hexponent : 1 ≤ n - 2 := by omega
      simpa using
        (Nat.pow_le_pow_right (n := 2) (by omega : 0 < 2) hexponent)
    omega
  obtain ⟨v, hv, hvzero⟩ := Finset.exists_mem_ne hcard (0 : FABL.F₂Cube n)
  exact ⟨v, hvzero, (mem_support f v).mp hv⟩

private theorem exists_nonzero_eq_zero_of_isBent
    (f : BooleanFunction n) (hf : IsBent f) (hnEven : Even n) (hn : 4 ≤ n) :
    ∃ v : FABL.F₂Cube n, v ≠ 0 ∧ f v = 0 := by
  have hfComplement : IsBent (f + 1) := by
    have hone :
        FABL.affineFunction (1 : FABL.𝔽₂) (0 : FABL.F₂Cube n) = 1 := by
      funext x
      simp [FABL.affineFunction, FABL.f₂DotProduct]
    rw [← hone]
    exact (isBent_add_affineFunction_iff f 1 0).mpr hf
  obtain ⟨v, hvzero, hvone⟩ :=
    exists_nonzero_eq_one_of_isBent (f + 1) hfComplement hnEven hn
  refine ⟨v, hvzero, ?_⟩
  simp only [Pi.add_apply, Pi.one_apply] at hvone
  apply add_right_cancel (b := (1 : FABL.𝔽₂))
  simpa using hvone

private theorem supportCodewordWeight_eq_first_or_second_of_isBent
    (f : BooleanFunction n) (hf : IsBent f) (hn : 4 ≤ n)
    (v : FABL.F₂Cube n) (hv : v ≠ 0) :
    supportCodewordWeight f v = 2 ^ (n - 2) ∨
      supportCodewordWeight f v = hammingWeight f - 2 ^ (n - 2) := by
  have hfour := four_mul_supportCodewordWeight_eq f v hv
  have habs : (walshTransform f v).natAbs = (walshTransform f 0).natAbs := by
    rw [natAbs_walshTransform_eq_two_pow_half_of_isBent f hf v,
      natAbs_walshTransform_eq_two_pow_half_of_isBent f hf 0]
  have hsplit : (2 : ℤ) ^ n = 4 * (2 ^ (n - 2) : ℤ) := by
    rw [show n = (n - 2) + 2 by omega, pow_add]
    norm_num
    ring
  rcases Int.natAbs_eq_natAbs_iff.mp habs with heq | hneg
  · left
    rw [heq] at hfour
    exact_mod_cast (by omega :
      (supportCodewordWeight f v : ℤ) = 2 ^ (n - 2))
  · right
    have hzero := walshTransform_zero_eq_two_pow_sub_two_weight f
    rw [hneg, hzero] at hfour
    have hnat :
        4 * supportCodewordWeight f v + 2 ^ n = 4 * hammingWeight f := by
      exact_mod_cast (by omega :
        (4 : ℤ) * supportCodewordWeight f v + 2 ^ n =
          4 * hammingWeight f)
    have hsplitNat : 2 ^ n = 4 * 2 ^ (n - 2) := by
      exact_mod_cast hsplit
    omega

private theorem exists_nonzero_walshTransform_eq_zeroFrequency_of_isBent
    (f : BooleanFunction n) (hf : IsBent f) (hnEven : Even n) (hn : 4 ≤ n) :
    ∃ v : FABL.F₂Cube n, v ≠ 0 ∧
      walshTransform f v = walshTransform f 0 := by
  let d := bentDual f
  obtain ⟨vOne, hvOne, hdOne⟩ :=
    exists_nonzero_eq_one_of_isBent d (isBent_bentDual f hf) hnEven hn
  obtain ⟨vZero, hvZero, hdZero⟩ :=
    exists_nonzero_eq_zero_of_isBent d (isBent_bentDual f hf) hnEven hn
  change bentDual f vOne = 1 at hdOne
  change bentDual f vZero = 0 at hdZero
  by_cases hd0 : d 0 = 1
  · change bentDual f 0 = 1 at hd0
    refine ⟨vOne, hvOne, ?_⟩
    rw [walshTransform_eq_two_pow_half_mul_bitSignInt_bentDual f hf vOne,
      walshTransform_eq_two_pow_half_mul_bitSignInt_bentDual f hf 0,
      hdOne, hd0]
  · have hd0Zero : bentDual f 0 = 0 := by
      by_contra hzero
      exact hd0 (show d 0 = 1 from Fin.eq_one_of_ne_zero _ hzero)
    refine ⟨vZero, hvZero, ?_⟩
    rw [walshTransform_eq_two_pow_half_mul_bitSignInt_bentDual f hf vZero,
      walshTransform_eq_two_pow_half_mul_bitSignInt_bentDual f hf 0,
      hdZero, hd0Zero]

private theorem exists_nonzero_walshTransform_eq_neg_zeroFrequency_of_isBent
    (f : BooleanFunction n) (hf : IsBent f) (hnEven : Even n) (hn : 4 ≤ n) :
    ∃ v : FABL.F₂Cube n, v ≠ 0 ∧
      walshTransform f v = -walshTransform f 0 := by
  let d := bentDual f
  obtain ⟨vOne, hvOne, hdOne⟩ :=
    exists_nonzero_eq_one_of_isBent d (isBent_bentDual f hf) hnEven hn
  obtain ⟨vZero, hvZero, hdZero⟩ :=
    exists_nonzero_eq_zero_of_isBent d (isBent_bentDual f hf) hnEven hn
  change bentDual f vOne = 1 at hdOne
  change bentDual f vZero = 0 at hdZero
  by_cases hd0 : d 0 = 1
  · change bentDual f 0 = 1 at hd0
    refine ⟨vZero, hvZero, ?_⟩
    rw [walshTransform_eq_two_pow_half_mul_bitSignInt_bentDual f hf vZero,
      walshTransform_eq_two_pow_half_mul_bitSignInt_bentDual f hf 0,
      hdZero, hd0]
    simp [bitSignInt]
  · have hd0Zero : bentDual f 0 = 0 := by
      by_contra hzero
      exact hd0 (show d 0 = 1 from Fin.eq_one_of_ne_zero _ hzero)
    refine ⟨vOne, hvOne, ?_⟩
    rw [walshTransform_eq_two_pow_half_mul_bitSignInt_bentDual f hf vOne,
      walshTransform_eq_two_pow_half_mul_bitSignInt_bentDual f hf 0,
      hdOne, hd0Zero]
    simp [bitSignInt]

private theorem supportCodewordWeight_eq_first_of_walshTransform_eq
    (f : BooleanFunction n) (hn : 4 ≤ n)
    (v : FABL.F₂Cube n) (hv : v ≠ 0)
    (hwalsh : walshTransform f v = walshTransform f 0) :
    supportCodewordWeight f v = 2 ^ (n - 2) := by
  have hfour := four_mul_supportCodewordWeight_eq f v hv
  rw [hwalsh] at hfour
  have hsplit : (2 : ℤ) ^ n = 4 * (2 ^ (n - 2) : ℤ) := by
    rw [show n = (n - 2) + 2 by omega, pow_add]
    norm_num
    ring
  exact_mod_cast (by omega :
    (supportCodewordWeight f v : ℤ) = 2 ^ (n - 2))

private theorem supportCodewordWeight_eq_second_of_walshTransform_eq_neg
    (f : BooleanFunction n) (hn : 4 ≤ n)
    (v : FABL.F₂Cube n) (hv : v ≠ 0)
    (hwalsh : walshTransform f v = -walshTransform f 0)
    (hfirst : 2 ^ (n - 2) ≤ hammingWeight f) :
    supportCodewordWeight f v = hammingWeight f - 2 ^ (n - 2) := by
  have hfour := four_mul_supportCodewordWeight_eq f v hv
  have hzero := walshTransform_zero_eq_two_pow_sub_two_weight f
  rw [hwalsh, hzero] at hfour
  have hnat :
      4 * supportCodewordWeight f v + 2 ^ n = 4 * hammingWeight f := by
    exact_mod_cast (by omega :
      (4 : ℤ) * supportCodewordWeight f v + 2 ^ n =
        4 * hammingWeight f)
  have hsplit : 2 ^ n = 4 * 2 ^ (n - 2) := by
    rw [show n = (n - 2) + 2 by omega, pow_add]
    norm_num
    ring
  omega

/-- Carlet Proposition 16, with the necessary correction `n ≥ 4`: a
Boolean function in positive even dimension is bent exactly when its
support-column code has dimension `n` and exactly the two stated nonzero
weights. -/
theorem isBent_iff_supportCode_finrank_and_two_nonzero_weights
    (f : BooleanFunction n) (hnEven : Even n) (hn : 4 ≤ n) :
    IsBent f ↔
      Module.finrank FABL.𝔽₂ (supportCode f) = n ∧
        SupportCodeHasExactlyTwoNonzeroWeights f := by
  constructor
  · intro hf
    have hfirstlt :=
      two_pow_sub_two_lt_hammingWeight_of_isBent f hf hnEven hn
    have hinjective : Function.Injective (supportCodeMap f) := by
      rw [← LinearMap.ker_eq_bot]
      apply le_antisymm
      · intro v hv
        change v = 0
        have hmap : supportCodeMap f v = 0 := hv
        by_contra hvzero
        have hweightZero : supportCodewordWeight f v = 0 := by
          rw [supportCodewordWeight, hmap, hammingNorm_zero]
        rcases supportCodewordWeight_eq_first_or_second_of_isBent
            f hf hn v hvzero with hfirst | hsecond
        · rw [hweightZero] at hfirst
          exact (Nat.ne_of_gt (Nat.two_pow_pos (n - 2))) hfirst.symm
        · rw [hweightZero] at hsecond
          omega
      · exact bot_le
    refine ⟨(finrank_supportCode_eq_n_iff_injective f).mpr hinjective, ?_⟩
    refine ⟨?_, ?_, ?_⟩
    · rintro ⟨c, hc⟩ hcne
      obtain ⟨v, rfl⟩ := hc
      have hv : v ≠ 0 := by
        intro hvzero
        subst v
        apply hcne
        apply Subtype.ext
        simp
      simpa [supportCodewordWeight] using
        supportCodewordWeight_eq_first_or_second_of_isBent f hf hn v hv
    · obtain ⟨v, hv, hwalsh⟩ :=
        exists_nonzero_walshTransform_eq_zeroFrequency_of_isBent
          f hf hnEven hn
      let c : supportCode f := ⟨supportCodeMap f v, ⟨v, rfl⟩⟩
      refine ⟨c, ?_, ?_⟩
      · intro hc
        have hvalue : supportCodeMap f v = 0 := by
          simpa [c] using congrArg Subtype.val hc
        exact hv (hinjective (by simpa using hvalue))
      · exact supportCodewordWeight_eq_first_of_walshTransform_eq
          f hn v hv hwalsh
    · obtain ⟨v, hv, hwalsh⟩ :=
        exists_nonzero_walshTransform_eq_neg_zeroFrequency_of_isBent
          f hf hnEven hn
      let c : supportCode f := ⟨supportCodeMap f v, ⟨v, rfl⟩⟩
      refine ⟨c, ?_, ?_⟩
      · intro hc
        have hvalue : supportCodeMap f v = 0 := by
          simpa [c] using congrArg Subtype.val hc
        exact hv (hinjective (by simpa using hvalue))
      · exact supportCodewordWeight_eq_second_of_walshTransform_eq_neg
          f hn v hv hwalsh hfirstlt.le
  · rintro ⟨hdimension, hweights⟩
    have hinjective : Function.Injective (supportCodeMap f) :=
      (finrank_supportCode_eq_n_iff_injective f).mp hdimension
    obtain ⟨cSecond, hcSecond, hweightSecond⟩ := hweights.2.2
    have hsecondPositive : 0 < hammingWeight f - 2 ^ (n - 2) := by
      rw [← hweightSecond]
      exact hammingNorm_pos_iff.mpr (by
        intro hzero
        apply hcSecond
        exact Subtype.ext hzero)
    have hfirst : 2 ^ (n - 2) < hammingWeight f :=
      Nat.sub_pos_iff_lt.mp hsecondPositive
    have hwalshSign (v : FABL.F₂Cube n) :
        walshTransform f v = walshTransform f 0 ∨
          walshTransform f v = -walshTransform f 0 := by
      by_cases hv : v = 0
      · exact Or.inl (by rw [hv])
      · let c : supportCode f := ⟨supportCodeMap f v, ⟨v, rfl⟩⟩
        have hc : c ≠ 0 := by
          intro hzero
          have hvalue : supportCodeMap f v = 0 := by
            simpa [c] using congrArg Subtype.val hzero
          exact hv (hinjective (by simpa using hvalue))
        have hword := hweights.1 c hc
        change supportCodewordWeight f v = 2 ^ (n - 2) ∨
          supportCodewordWeight f v = hammingWeight f - 2 ^ (n - 2) at hword
        have hfour := four_mul_supportCodewordWeight_eq f v hv
        have hsplit : (2 : ℤ) ^ n = 4 * (2 ^ (n - 2) : ℤ) := by
          rw [show n = (n - 2) + 2 by omega, pow_add]
          norm_num
          ring
        rcases hword with hword | hword
        · left
          have hwordInt :
              (supportCodewordWeight f v : ℤ) = (2 ^ (n - 2) : ℤ) := by
            exact_mod_cast hword
          rw [hwordInt] at hfour
          omega
        · right
          have hwordInt :
              (supportCodewordWeight f v : ℤ) =
                (hammingWeight f : ℤ) - (2 ^ (n - 2) : ℤ) := by
            calc
              (supportCodewordWeight f v : ℤ) =
                  (hammingWeight f - 2 ^ (n - 2) : ℕ) := by
                exact_mod_cast hword
              _ = (hammingWeight f : ℤ) - (2 ^ (n - 2) : ℤ) := by
                rw [Nat.cast_sub hfirst.le]
                norm_num only [Nat.cast_pow, Nat.cast_ofNat]
          rw [hwordInt] at hfour
          have hzero := walshTransform_zero_eq_two_pow_sub_two_weight f
          omega
    have hparseval := sum_walshTransform_sq_eq_two_pow_sq f
    have hconstantSum :
        (∑ v : FABL.F₂Cube n, (walshTransform f v : ℝ) ^ 2) =
          (2 : ℝ) ^ n * (walshTransform f 0 : ℝ) ^ 2 := by
      calc
        (∑ v : FABL.F₂Cube n, (walshTransform f v : ℝ) ^ 2) =
            ∑ _v : FABL.F₂Cube n, (walshTransform f 0 : ℝ) ^ 2 := by
          apply Finset.sum_congr rfl
          intro v _hv
          rcases hwalshSign v with heq | hneg
          · rw [heq]
          · rw [hneg]
            norm_num only [Int.cast_neg]
            ring
        _ = (2 : ℝ) ^ n * (walshTransform f 0 : ℝ) ^ 2 := by
          rw [Finset.sum_const, Finset.card_univ, card_f₂Cube, nsmul_eq_mul]
          norm_num
    have hsquare :
        (walshTransform f 0 : ℝ) ^ 2 = (2 : ℝ) ^ n := by
      rw [hconstantSum] at hparseval
      apply mul_left_cancel₀ (by positivity : (2 : ℝ) ^ n ≠ 0)
      calc
        (2 : ℝ) ^ n * (walshTransform f 0 : ℝ) ^ 2 =
            ((2 : ℝ) ^ n) ^ 2 := hparseval
        _ = (2 : ℝ) ^ n * (2 : ℝ) ^ n := by ring
    have habsZero :
        |(walshTransform f 0 : ℝ)| = (2 : ℝ) ^ (n / 2) := by
      apply (sq_eq_sq₀ (abs_nonneg _) (by positivity)).mp
      rw [sq_abs, hsquare]
      rcases hnEven with ⟨k, rfl⟩
      have hhalf : (k + k) / 2 = k := by omega
      rw [hhalf, pow_add]
      ring
    apply (isBent_iff_forall_natAbs_walshTransform_eq_two_pow_half f).mpr
    intro v
    have habs :
        |(walshTransform f v : ℝ)| = (2 : ℝ) ^ (n / 2) := by
      rcases hwalshSign v with heq | hneg
      · rw [heq, habsZero]
      · rw [hneg]
        norm_num only [Int.cast_neg]
        rw [abs_neg, habsZero]
    apply Nat.cast_injective (R := ℝ)
    simpa only [Nat.cast_natAbs, Int.cast_abs, Nat.cast_pow,
      Nat.cast_ofNat] using habs

end CryptBoolean
